import Vue from 'vue';
import BaseSearchForm from './base-search-form';
import BaseInput from './base-input';
import BaseMarkdown from './base-markdown';
import BaseSelect from './base-select';
import BaseDaterange from './base-daterange';
import BaseTable from './base-table';
import BaseModal from './base-modal';
import BaseForm from './base-form';
import BaseAuthCode from './base-auth-code';
import BaseAvatar from './base-avatar';

Vue.component('BaseSearchForm', BaseSearchForm);
Vue.component('BaseInput', BaseInput);
Vue.component('BaseMarkdown', BaseMarkdown);
Vue.component('BaseSelect', BaseSelect);
Vue.component('BaseDaterange', BaseDaterange);
Vue.component('BaseTable', BaseTable);
Vue.component('BaseModal', BaseModal);
Vue.component('BaseForm', BaseForm);
Vue.component('BaseAuthCode', BaseAuthCode);
Vue.component('BaseAvatar', BaseAvatar);
